#!/bin/sh

# Need to use use autoconf >= 2.50 an automake >= 1.5.  This allows user to
# set these variables in their environment, or to just use the defaults below.
# This is needed since some systems still use autoconf-2.13 and automake-1.4 as
# the defaults (e.g. debian).

: ${ACLOCAL=aclocal}
: ${AUTOMAKE=automake}
: ${AUTOCONF=autoconf}
: ${AUTOHEADER=autoheader}

set -e

set -x
(
    ${ACLOCAL}
    ${AUTOCONF}
    [ -d config-aux ] || mkdir config-aux
    ${AUTOMAKE} -a -c

    cd src
    ${ACLOCAL}
    ${AUTOHEADER}
    ${AUTOCONF}
    ${AUTOMAKE}
    cd ..
)
rm -f config.cache src/config.cache
