.TH START-AVARICE 1 "2015-04-10"
.SH NAME
start-avarice \- launch avarice in detached mode
.SH SYNOPSIS
.B start-avarice
.RI [ file ]
.SH DESCRIPTION
\fBstart-avarice\fR is a helper to launch \fBavarice\fR in detached mode.
\fBavarice\fR will be listening in GDB mode on local port \fB6423\fR. You can
then connect from \fBavr-gdb\fR like so:
.IP
(gdb) target remote localhost:6423
.PP
Other running instances of \fBavarice\fP are killed first.

If the optional argument \fIfile\fR is specified, the target is first
erased, and then programmed with this file. Note that this feature has
been deprecated though, and may disappear anytime in the future.
.SH ENVIRONMENT
.IP AVARICE_ARGS
Additional arguments to pass on to \fBavarice\fR.
.SH SEE ALSO
.BR avarice (1),
.BR gdb (1),
.BR kill-avarice (1).
