name: Build Binaries
on: [push, pull_request]

jobs:
  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: false
          install: git make gcc libtool msys/autotools msys/autoconf-wrapper automake cmake msys/binutils mingw-w64-x86_64-libusb mingw-w64-x86_64-libusb-win32 mingw-w64-x86_64-hidapi
      - name: CI-Build
        run: |
          ./Bootstrap
          ./configure
          make -j4
          make install DESTDIR=$(pwd)/avarice_installed/
          file avarice_installed/usr/local/bin/*
          ldd avarice_installed/usr/local/bin/avarice
          cp /mingw64/bin/libusb-1.0.dll avarice_installed/usr/local/bin/.
          avarice_installed/usr/local --known-devices || true
      - uses: actions/upload-artifact@v3
        with:
          name: Windows 64-bit
          path: avarice_installed
  build-lin64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependenncies
        run: sudo apt-get install -y build-essential make autotools-dev automake binutils-dev libusb-dev libhidapi-dev
      - name: CI-Build
        run: |
          ./Bootstrap
          ./configure --enable-target-programming
          make -j4
          mkdir avarice_installed
          make install DESTDIR=$(pwd)/avarice_installed/
          file avarice_installed/usr/local/bin/*
          ldd avarice_installed/usr/local/bin/avarice
          avarice_installed/usr/local --known-devices || true
      - name: Tar files
        run: tar -cvf avarice.tar.gz -C avarice_installed/usr/local/bin .
      - uses: actions/upload-artifact@v3
        with:
          name: Linux 64-bit
          path: avarice.tar.gz